const databaseOptions = ["default", "customed"];
const connectionModeOptions = ["Top 5", "Top 10", "Top 15", "Top 20"];
const mathingOptions = [
  "modified cosine",
  "neutral loss",
  "peak percentage",
  "entropy",
  "unweighted_entropy",
  "euclidean",
  "manhattan",
  "chebyshev",
  "squared_euclidean",
  "fidelity",
  "matusita",
  "squared_chord",
  "bhattacharya_1",
  "bhattacharya_2",
  "harmonic_mean",
  "probabilistic_symmetric_chi_squared",
  "ruzicka",
  "roberts",
  "intersection",
  "motyka",
  "canberra",
  "baroni_urbani_buser",
  "penrose_size",
  "mean_character",
  "lorentzian",
  "penrose_shape",
  "clark",
  "hellinger",
  "whittaker_index_of_association",
  "symmetric_chi_squared",
  "pearson_correlation",
  "improved_similarity",
  "absolute_value",
  "dot_product",
  "dot_product_reverse",
  "spectral_contrast_angle",
  "wave_hedges",
  "cosine",
  "jaccard",
  "dice",
  "inner_product",
  "divergence",
  "avg_l",
  "vicis_symmetric_chi_squared_3",
  "ms_for_id_v1",
  "ms_for_id",
  "weighted_dot_product",
];

export {databaseOptions, connectionModeOptions, mathingOptions}